### ISSUE TITLE
Failed to activate the swackets package

### ISSUE THREAD

**Issue by cbilliau** [jrattray13/swackets#25]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.0
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: [swackets](https://github.com/jrattray13/swackets) package, v0.12.0

### Stack Trace

Failed to activate the swackets package

```
At Invalid regular expression: /(?<!\\)(?:[$%#].?)?[\{]/: Invalid group

SyntaxError: Invalid regular expression: /(?<!\\)(?:[$%#].?)?[\{]/: Invalid group
    at RegExp (native)
    at SwacketsView.module.exports.SwacketsView.config (/Users/cbilliau/.atom/packages/swackets/lib/swackets-view.coffee:64:26)
    at new SwacketsView (/Users/cbilliau/.atom/packages/swackets/lib/swackets-view.coffee:13:19)
    at Object.activate (/Users/cbilliau/.atom/packages/swackets/lib/swackets.coffee:32:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:548:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:529:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:506:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:783:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-javascript",
      "linter-jshint"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.5 (inactive)
atom-beautify, v0.29.13 (inactive)
atom-typescript, v10.1.12 (inactive)
dash, v1.7.0 (inactive)
emmet, v2.4.3 (inactive)
emmet-simplified, v2.5.0 (inactive)
emmet-snippets-compatibility, v1.0.6 (inactive)
file-icons, v1.7.24 (inactive)
highlight-selected, v0.11.2 (inactive)
language-babel, v2.48.1 (inactive)
linter, v1.11.18 (inactive)
linter-jshint, v3.0.1 (inactive)
lipsum, v0.1.0 (inactive)
minimap, v4.25.6 (inactive)
minimap-highlight-selected, v4.4.0 (inactive)
pigments, v0.37.0 (inactive)
script, v3.11.1 (inactive)
swackets, v0.12.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.0 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.1 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.3 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.46.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by cbilliau** [comment]
sorry. Atom sccessfully did a rebuild.

**Comment by Arcath** [comment]
I'm getting the same issue. @cbilliau what did you do to fix it?

**Comment by cbilliau** [comment]
Sorry. The same error is back now.

**Comment by Arcath** [comment]
This is the same issue as #24

**Comment by cbilliau** [comment]
ok. ill note that and close it. thanks
Chris Billiau
christopher@billiau.com

**Comment by cbilliau** [comment]
This is the same issue as #24

**Comment by Jakub41** [comment]
Hello I have this error and also after rebuild is not working:
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.0
**Electron Version**: 1.3.6
**System**: Ubuntu 16.04.1
**Thrown From**: [swackets](https://github.com/jrattray13/swackets) package, v0.12.0


### Stack Trace

Failed to activate the swackets package

```
At Invalid regular expression: /(?<!\\)(?:[$%#].?)?[\{]/: Invalid group

SyntaxError: Invalid regular expression: /(?<!\\)(?:[$%#].?)?[\{]/: Invalid group
    at RegExp (native)
    at SwacketsView.module.exports.SwacketsView.config (/home/jakub/.atom/packages/swackets/lib/swackets-view.coffee:64:26)
    at new SwacketsView (/home/jakub/.atom/packages/swackets/lib/swackets-view.coffee:13:19)
    at Object.activate (/home/jakub/.atom/packages/swackets/lib/swackets.coffee:32:21)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:184:19)
    at /opt/atom/resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at /opt/atom/resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:548:21)
    at /opt/atom/resources/app.asar/src/package-manager.js:529:29
    at Config.module.exports.Config.transactAsync (/opt/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/atom/resources/app.asar/src/package-manager.js:524:19)
    at PackageManager.module.exports.PackageManager.activate (/opt/atom/resources/app.asar/src/package-manager.js:506:46)
    at /opt/atom/resources/app.asar/src/atom-environment.js:783:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "atom-htmltidy",
      "terminal-plus"
    ],
    "packagesWithKeymapsDisabled": [],
    "telemetryConsent": "limited",
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-new-file, v0.5.0 (inactive)
advanced-open-file, v0.16.4 (inactive)
atom-beautify, v0.29.13 (inactive)
atom-css-comb, v3.1.0 (inactive)
atom-html-preview, v0.1.22 (inactive)
atom-monokai, v0.10.4 (inactive)
atom-prettify, v0.1.3 (inactive)
atom-ternjs, v0.15.0 (inactive)
auto-detect-indentation, v1.3.0 (inactive)
autoclose-html, v0.23.0 (inactive)
autocomplete-html-entities, v0.1.0 (inactive)
autocomplete-modules, v1.6.7 (inactive)
autocomplete-python, v1.8.11 (inactive)
autoprefixer, v3.3.0 (inactive)
browser-plus, v0.0.76 (inactive)
color-picker, v2.2.2 (inactive)
config-import-export, v0.3.1 (inactive)
editorconfig, v2.0.5 (inactive)
emmet, v2.4.3 (inactive)
exception-reporting, v0.40.0 (inactive)
file-icons, v1.7.24 (inactive)
git-plus, v5.25.0 (inactive)
git-time-machine, v1.5.3 (inactive)
highlight-selected, v0.11.2 (inactive)
jquery-snippets, v11.0.0 (inactive)
language-babel, v2.48.1 (inactive)
less-autocompile, v1.0.0 (inactive)
linter, v1.11.18 (inactive)
linter-sass-lint, v1.7.4 (inactive)
linter-scss-lint, v3.0.4 (inactive)
metrics, v1.1.1 (inactive)
minimap, v4.25.6 (inactive)
minimap-highlight-selected, v4.4.0 (inactive)
open-recent, v5.0.0 (inactive)
pandoc, v0.2.2 (inactive)
php-cs-fixer, v2.5.9 (inactive)
pigments, v0.37.0 (inactive)
project-manager, v3.3.3 (inactive)
python-autopep8, v0.1.3 (inactive)
python-indent, v1.0.0 (inactive)
python-tools, v0.6.8 (inactive)
sass-autocompile, v0.13.1 (inactive)
script, v3.11.1 (inactive)
seti-icons, v1.3.4 (inactive)
seti-ui, v1.3.2 (inactive)
spacegray-atom-dark-ui, v1.0.0 (inactive)
swackets, v0.12.0 (inactive)
sync-settings, v0.7.2 (inactive)
terminal-fusion, v2.4.2 (inactive)
todo-show, v1.8.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
find-and-replace, v0.202.0 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.3 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.46.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by rayk** [comment]
[Enter steps to reproduce below:]

1. Just starting up atom... 
2. Swackets fails with.. Invalid regular expression: /(?<!\\)(?:[$%#].?)?[\{\(\[]/: Invalid group

**Atom Version**: 1.12.1
**Electron Version**: 1.3.6
**System**: Mac OS X 10.12.1
**Thrown From**: [swackets](https://github.com/jrattray13/swackets) package, v0.12.0


### Stack Trace

Failed to activate the swackets package

```
At Invalid regular expression: /(?<!\\)(?:[$%#].?)?[\{\(\[]/: Invalid group

SyntaxError: Invalid regular expression: /(?<!\\)(?:[$%#].?)?[\{\(\[]/: Invalid group
    at RegExp (native)
    at SwacketsView.module.exports.SwacketsView.config (/Users/rayk/.atom/packages/swackets/lib/swackets-view.coffee:64:26)
    at new SwacketsView (/Users/rayk/.atom/packages/swackets/lib/swackets-view.coffee:13:19)
    at Object.activate (/Users/rayk/.atom/packages/swackets/lib/swackets.coffee:32:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:548:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:529:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:506:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:783:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "background-tips",
      "language-csharp",
      "language-objective-c",
      "language-php",
      "language-ruby-on-rails",
      "language-toml",
      "package-generator",
      "welcome",
      "language-perl",
      "language-c",
      "dev-live-reload"
    ],
    "followSymlinks": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".pioenvs",
      ".piolibdeps",
      ".clang_complete",
      ".gcc-flags.json"
    ],
    "projectHome": "~/Projects",
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "useCustomTitleBar": true
  },
  "swackets": {
    "colorParens": true,
    "colorSquareBrackets": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (inactive)
auto-update-packages, v1.0.1 (inactive)
autoclose-html, v0.23.0 (inactive)
autocomplete-html-entities, v0.1.0 (inactive)
autocomplete-java, v1.2.5 (inactive)
bleen-syntax, v0.3.1 (inactive)
borealis-syntax, v0.6.0 (inactive)
clock, v1.7.2 (inactive)
clojure-plus, v0.1.2 (inactive)
color-tabs, v0.1.8 (inactive)
css-clean, v2.15.0 (inactive)
dark-bint-syntax, v0.8.9 (inactive)
dash, v1.7.0 (inactive)
file-icons, v1.7.24 (inactive)
foldingtext-for-atom, v0.9.2 (inactive)
genesis-ui, v0.5.0 (inactive)
git-control, v0.8.2 (inactive)
git-log, v0.4.1 (inactive)
git-status, v0.3.4 (inactive)
git-time-machine, v1.5.3 (inactive)
gitignore-snippets, v0.2.5 (inactive)
golden-ratio, v0.3.0 (inactive)
highlight-line, v0.11.1 (inactive)
highlight-selected, v0.11.2 (inactive)
imdone-atom, v2.0.15 (inactive)
ink, v0.5.3 (inactive)
jumpy, v3.1.3 (inactive)
language-ini, v1.16.0 (inactive)
line-count, v0.5.0 (inactive)
line-count-status, v0.0.3 (inactive)
lines, v0.13.1 (inactive)
linter, v1.11.18 (inactive)
linter-clojure, v1.1.2 (inactive)
linter-javac, v1.9.4 (inactive)
linter-sass-lint, v1.7.4 (inactive)
lisp-paredit, v0.5.4 (inactive)
markdown-format, v2.5.1 (inactive)
northem-dark-atom-syntax, v2.0.0 (inactive)
pane-jump, v0.2.0 (inactive)
Parinfer, v1.16.0 (inactive)
pigments, v0.37.0 (inactive)
project-manager, v3.3.3 (inactive)
proto-repl, v1.4.8 (inactive)
proto-repl-charts, v0.4.0 (inactive)
sass-autocompile, v0.13.1 (inactive)
set-syntax, v0.3.2 (inactive)
soft-charcoal-syntax, v0.1.0 (inactive)
sort-lines, v0.14.0 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (inactive)
swackets, v0.12.0 (inactive)
sync-settings, v0.7.2 (inactive)
tab-switcher, v1.5.4 (inactive)
tablr, v1.5.5 (inactive)
tool-bar, v1.0.1 (inactive)
tool-bar-main, v0.0.10 (inactive)
tree-view-git-status, v1.2.0 (inactive)
wakatime, v6.0.10 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.1 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.46.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by robcazin** [comment]
same here. still broken

![screen shot 2017-02-23 at 2 04 58 pm](https://cloud.githubusercontent.com/assets/15057009/23274550/23c0267e-f9d1-11e6-97b1-5a3d9b479df4.png)
