### ISSUE TITLE
Uncaught TypeError: _this.toggle is not a function

### ISSUE THREAD

**Issue by paradox460** [jrattray13/swackets#7]
1. Command Palette
2. Toggle Swackets

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [swackets](https://github.com/jrattray13/swackets) package, v0.6.0

### Stack Trace

Uncaught TypeError: _this.toggle is not a function

```
At ~/.atom/packages/swackets/lib/swackets-view.coffee:27

TypeError: _this.toggle is not a function
  at atom-workspace.SwacketsView.subscriptions.add.atom.commands.add.swackets:toggle (~/.atom/packages/swackets/lib/swackets-view.coffee:27:87)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:20)

```

### Commands

```
     -0:09.9.0 command-palette:toggle (atom-text-editor.editor.is-focused.vim-mode.insert-mode)
     -0:07.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.0 swackets:toggle (atom-text-editor.editor.vim-mode.insert-mode)
     -0:02.0 command-palette:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "quantum-ui",
      "base16-tomorrow-dark-theme"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-alignment, v0.12.1
auto-indent, v0.5.0
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
bezier-curve-editor, v0.7.2
color-picker, v2.0.13
column-select, v0.2.0
file-icons, v1.6.11
foldingtext-for-atom, v0.9.2
foldingtext-markdown, v1.3.2
grammar-token-limit, v0.1.1
highlight-column, v0.5.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
html-entities, v0.4.0
indentation-indicator, v0.6.0
language-diff, v0.3.1
language-fish-shell, v1.0.2
language-generic-config, v0.2.0
language-haml, v0.23.4
language-pfm, v0.82.0
language-rspec, v0.3.0
language-slim, v0.5.0
linter, v1.10.0
linter-coffeelint, v1.1.2
linter-haml, v1.0.0
linter-js-yaml, v1.2.0
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-rubocop, v0.4.4
linter-slim, v1.0.0
linter-xmllint, v0.0.7
markdown-scroll-sync, v0.4.2
minimap, v4.16.0
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
pain-split, v1.4.0
project-manager, v2.6.5
quantum-ui, v0.2.2
red-wavy-underline, v0.3.0
ruby-block, v0.3.5
set-syntax, v0.3.0
swackets, v0.6.0
swap-panes, v0.2.0
symbols-tree-view, v0.10.1
sync-settings, v0.6.0
tablr, v0.6.1
tabs-to-spaces, v0.11.1
underline-trailing-whitespace, v1.4.0
vim-mode, v0.63.0
vim-surround, v0.8.0
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by jrattray13** [comment]
Sorry for delay, should be fixed in 0.8 release :+1:
